# Generated by Django 4.2.21 on 2025-05-27 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_preferences', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpreferencesdata',
            options={'verbose_name_plural': 'user preferences data'},
        ),
        migrations.AlterModelOptions(
            name='usersettings',
            options={'verbose_name_plural': 'user settings'},
        ),
        migrations.AlterField(
            model_name='userpreferencesdata',
            name='complementary_email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='E-Mail (complementary)'),
        ),
        migrations.AlterField(
            model_name='userpreferencesdata',
            name='email',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='userpreferencesdata',
            name='fax',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='userpreferencesdata',
            name='gnd_viaf',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='userpreferencesdata',
            name='orcid_pid',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='userpreferencesdata',
            name='position',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='userpreferencesdata',
            name='showroom_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='userpreferencesdata',
            name='telephone',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='userpreferencesdata',
            name='urls',
            field=models.URLField(blank=True, default='', max_length=255, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='usersettingsapp',
            name='icon',
            field=models.URLField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='usersettingsapp',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, unique=True),
        ),
    ]
